"use client"
import type { Metadata } from "next";
import "./globals.css";
import useQuiz from "./store";

// export const metadata: Metadata = {
//   title: "Quiz App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  quiz,
}: {
  children: React.ReactNode;
  quiz: React.ReactNode;
}) {
  const config = useQuiz((state) => state.config);
  let render = config.status === "start" ? quiz:children
  return (
    <html lang="en">
      <body>{render}</body>
    </html>
  );
}
